language: perl
perl:
 - "5.18"
before_install:
#note: might need cleanup here and there
#install xlsx writer module
  - sudo apt install -qq libexcel-writer-xlsx-perl
install:
  - echo "Hello world" > file.tsv
  - perl tableToXlsxAsStrings.pl \\t file.tsv
  - perl tableToXlsxAsStrings.pl \\t file.tsv
  - base64 file*.xlsx
  - echo "use it from the source dir"
