language: perl
#perl:
# - "5.18"
before_install:
  - "cpanm --installdeps --notest . || (tail -n 5000 /home/travis/.cpanm/work/*/build.log && exit 1)
script:
  - echo "Hello world" > file.tsv
  - tableToXlsxAsStrings.pl \\t file.tsv
  - tableToXlsxAsStrings.pl \\t file.tsv
  - base64 file*.xlsx
  - echo "use it from the source dir"
